### ISSUE TITLE
Kick this thing off

### ISSUE THREAD

**Issue by david-pm** [david-pm/weirdkids#1]
Nelson,

1. Should we use Gulp or Grunt?

2. How do you feel about [this little framework](http://designmodo.github.io/Flat-UI/) for css? It'd make it quick to just throw some stuff together. Or do you want to just stick with Bootstrap? I'm fine with even going without I framework. I'm thinking we just want to stick with the functionality first. 

3. Let's do something with Angular and Firebase. Agreed?

4. What should we build? I'm thinking something that requires a user to login/register and then create their own simple drawing like you can do in google chat. Very basic sketches with the mouse, basic colors, which they can then upload. They can simply draw, name, and submit. Then they can see their drawing in the gallery section or something. How's that all sound, boy-o?

**Comment by NelsonWells** [comment]
1. I've never used Gulp or Grunt and would need a primer for each, so choose what you like and I'll learn it. 
2. That flat UI is fantastic let's do it. 
3. Angular and Firebase works. 
4. Let's make a collector. Basically cells that can be edited and use the flat UI. Treat them as collectable cards. Elements in the containers would include simple Title, Subtitle, Image, Notes, and Region. There could be a search bar. I've already made that part in angular sooo..... 
{ Or a GAME!!!!!  Some of the really good ones have one programmer and one graphics dude and one musician. We have two programmers and even more artists and musicians. Game is big though so we should do something little first. If you're interested in that, download xcode it's free poke around and Simon Allardice does the classes on Lynda so they're engaging and worth it.  We could the game in JavaScript too. Whatevs. }

**Comment by david-pm** [comment]
Cool, cool, cool. 
4. (revisited) - Ok, ok. So, I'm into doing a game, but later. I just want to make a simple-ish web app so that we can see how we are able to collaborate on a project, and if we can bring something to completion, or not. So, let's go with the collector idea. 
Let me make sure I understand the concept: People can make their own cards, complete with Title, drawing, etc., and then other users can add them to their personal galleries if they like? If so, then cool.
___

## ToDo
-We need to wire-frame this whole thing out 
-We need to know how many views (pages) we are going to need. 
-Need to design database schemas
-Buttplugs

**Comment by NelsonWells** [comment]
It would be a framework for a beer collector where you can upload a photo you've taken of your beer (ie: New Belgium, Fat Tire, with a photo of the beer or one I've drawn of it or whatever.) The UI could feel like collectable cards. We could use the framework we create to cater to other peoples desires, such as "I want to collect all the Pugs I meet" or all the weeds I smoke or tattoo ideas, or times I caught Ricmo running around naked or whatever. The cool part would be that it felt like cards to collect and we could start with beers, but really the content is up to the user... unless we package all of them individually and push them as separate items under the same framework. Key part for us to design is the foundation. Zang?

**Comment by david-pm** [comment]
Dude, that is perfect. Okay, I'm gonna set up the basic structure and tooling sometime this week.
